# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170110_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conarq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codGrupo', models.IntegerField(unique=True)),
                ('codigo', models.IntegerField(unique=True)),
                ('assunto', models.CharField(max_length=50, null=True)),
                ('faseCorrente', models.CharField(max_length=50, null=True)),
                ('faseIntermediaria', models.CharField(max_length=50, null=True)),
                ('destinacaoFinal', models.CharField(max_length=50, null=True)),
                ('observacoes', models.TextField(null=True)),
            ],
        ),
    ]
