# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_conarq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conarq',
            name='codGrupo',
            field=models.IntegerField(),
        ),
    ]
