# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170116_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('observacoes', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='conarq',
            old_name='codigo',
            new_name='cod',
        ),
        migrations.AddField(
            model_name='resposta',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo', to='app.Conarq'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='app.Conarq'),
        ),
    ]
