# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170116_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConarq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='conarq',
            name='codGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codGrupo', to='app.GrupoConarq'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='app.GrupoConarq'),
        ),
    ]
