# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170116_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conarq',
            name='codGrupo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='app.Conarq'),
        ),
        migrations.DeleteModel(
            name='GrupoConarq',
        ),
    ]
