# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170116_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conarq',
            name='assunto',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='conarq',
            name='destinacaoFinal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='conarq',
            name='faseCorrente',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='conarq',
            name='faseIntermediaria',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='grupoconarq',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
