# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20161108_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipologia',
            old_name='identificação',
            new_name='identificacao',
        ),
    ]
