# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161121_1029'),
        ('app', '0016_tipologia_sugestao'),
    ]

    operations = [
    ]
